require "tg.options"
require "tg.keymaps"
require "tg.plugins"
require "tg.lualine"
require "tg.bufferline"
require "tg.nvimtree"
require "tg.cmp"
require "tg.treesitter"
require "tg.tel"
require "tg.lsp_config"

-- vim.cmd "colorscheme tokyonight"
vim.cmd "colorscheme gruvbox"
vim.cmd "colorscheme gruvbox"
